CANLibrary: CAN::CSendCANFrame Class Reference
CAN::CSendCANFrame Class Reference
#include "CSendCANFrame.h"
Public Member Functions
CSendCANFrame (unsigned long pAddress, unsigned char pD0=0x0, unsigned char pD1=0x0, unsigned char pD2=0x0, unsigned char pD3=0x0, unsigned char pD4=0x0, unsigned char pD5=0x0, unsigned char pD6=0x0, unsigned char pD7=0x0)
virtual unsigned char GetLength () const override
virtual unsigned long GetAddress () const override
virtual const unsigned char *const GetData () const override
bool SendTo (ICANConnector &pCAN) const
Public Member Functions inherited from CAN::ACANFrame
virtual ~ACANFrame ()
void Print () const
Protected Attributes
unsigned char mLength
unsigned long mAddress
unsigned char mData [CAN_FRAME_LENGHT]
Detailed Description
A frame used to send CAN data
Definition at line 17 of file CSendCANFrame.h.
Constructor & Destructor Documentation
CSendCANFrame()
CAN::CSendCANFrame::CSendCANFrame (unsigned long pAddress, unsigned char pD0 = 0x0, unsigned char pD1 = 0x0, unsigned char pD2 = 0x0, unsigned char pD3 = 0x0, unsigned char pD4 = 0x0, unsigned char pD5 = 0x0, unsigned char pD6 = 0x0, unsigned char pD7 = 0x0) inline
Constructor
Parameters
[in] pAddress Frame address
[in] pD0 Data 0
[in] pD1 Data 1
[in] pD2 Data 2
[in] pD3 Data 3
[in] pD4 Data 4
[in] pD5 Data 5
[in] pD6 Data 6
[in] pD7 Data 6
Definition at line 32 of file CSendCANFrame.h.
References mAddress, mData, and mLength.
         {
             // Initialize address and length
             this->mAddress  = pAddress ;
             this->mLength   = CAN_FRAME_LENGHT ;
             // Initialize data
             this->mData[0]  = pD0 ;
             this->mData[1]  = pD1 ;
             this->mData[2]  = pD2 ;
             this->mData[3]  = pD3 ;
             this->mData[4]  = pD4 ;
             this->mData[5]  = pD5 ;
             this->mData[6]  = pD6 ;
             this->mData[7]  = pD7 ;
         }
Member Function Documentation
GetAddress()
virtual unsigned long CAN::CSendCANFrame::GetAddress () const inline override virtual
Gets frame address
Returns
Current frame address
Implements CAN::ACANFrame.
Definition at line 70 of file CSendCANFrame.h.
References mAddress.
Referenced by SendTo().
         {
             return this->mAddress ;
         }
GetData()
virtual const unsigned char* const CAN::CSendCANFrame::GetData () const inline override virtual
Gets data
Returns
Current data
Implements CAN::ACANFrame.
Definition at line 79 of file CSendCANFrame.h.
References mData.
Referenced by SendTo().
         {
             return this->mData ;
         }
GetLength()
virtual unsigned char CAN::CSendCANFrame::GetLength () const inline override virtual
Gets data length
Returns
Current data length
Implements CAN::ACANFrame.
Definition at line 61 of file CSendCANFrame.h.
References mLength.
Referenced by SendTo().
         {
             return this->mLength ;
         }
SendTo()
bool CAN::CSendCANFrame::SendTo (ICANConnector & pCAN) const inline
Sends data to the given CAN connector
Parameters
[in] pCAN CAN connector to use
Returns
True on success, false otherwise
Definition at line 89 of file CSendCANFrame.h.
References GetAddress(), GetData(), GetLength(), and CAN::ICANConnector::WaitSend().
Referenced by OBD::COBDFrame< ECombiBtnStatus >::SendAndUpdate().
         {
             return pCAN.WaitSend(this->GetAddress(), this->GetLength(), this->GetData()) ;
         }
Member Data Documentation
mAddress
unsigned long CAN::CSendCANFrame::mAddress protected
Frame address
Definition at line 96 of file CSendCANFrame.h.
Referenced by CSendCANFrame(), and GetAddress().
mData
unsigned char CAN::CSendCANFrame::mData[CAN_FRAME_LENGHT] protected
Data values
Definition at line 97 of file CSendCANFrame.h.
Referenced by CSendCANFrame(), and GetData().
mLength
unsigned char CAN::CSendCANFrame::mLength protected
Data length
Definition at line 95 of file CSendCANFrame.h.
Referenced by CSendCANFrame(), and GetLength().
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Frame/CAN/CSendCANFrame.h