CANLibrary: ICANConnector Class Reference
ICANConnector Class Reference abstract
#include "ICANConnector.h"
Public Member Functions
virtual bool Initialize ()=0
virtual bool SetMask (unsigned char pId, unsigned char pFrameType, unsigned long pMask)=0
virtual bool SetFilter (unsigned char pId, unsigned char pFrameType, unsigned long pFilter)=0
bool WaitHasMessages (unsigned long pTimeout=CAN_TIMEOUT)
virtual bool HasMessages ()=0
bool WaitRead (unsigned long &pCANId, unsigned char &pLength, unsigned char *pData, unsigned long pTimeout=CAN_TIMEOUT)
bool Read (unsigned long &pCANId, unsigned char &pLength, unsigned char *pData)
bool WaitSend (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData, unsigned long pTimeout=CAN_TIMEOUT)
bool Send (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData)
Protected Member Functions
virtual ~ICANConnector ()
virtual bool ReadImpl (unsigned long &pCANId, unsigned char &pLength, unsigned char *pReadData)=0
virtual bool SendImpl (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData)=0
void Print (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) const
Detailed Description
Interface through CAN library
Definition at line 15 of file ICANConnector.h.
Constructor & Destructor Documentation
~ICANConnector()
virtual ICANConnector::~ICANConnector () inline protected virtual
Destructor
Definition at line 21 of file ICANConnector.h.
References Initialize(), SetFilter(), and SetMask().
     {
     }
Member Function Documentation
HasMessages()
virtual bool ICANConnector::HasMessages () pure virtual
Tests if there is something to read or not
Returns
True if something, false otherwise
Implemented in CMCPCANConnector, and CDebugConnector.
Referenced by WaitHasMessages().
Initialize()
virtual bool ICANConnector::Initialize () pure virtual
Initialize the CAN bus
Returns
True on success, false otherwise
Implemented in CMCPCANConnector, and CDebugConnector.
Referenced by ~ICANConnector().
Print()
void ICANConnector::Print (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) const inline protected
Prints the frame content
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Definition at line 243 of file ICANConnector.h.
Referenced by Read(), and Send().
     {
         // Print address first
         PRINT("0x") ;
         PRINTHEX(pCANId) ;
         PRINT("\t") ;
         // Then each data
         for (int lDataIndex = 0 ; lDataIndex < pLength ; lDataIndex++)
         {
             PRINT(pData[lDataIndex] <= 0xF ? " 0x0" : " 0x") ;
             PRINTHEX(pData[lDataIndex]) ;
         }
         // And go next line
         PRINTLN("") ;
     }
Read()
bool ICANConnector::Read (unsigned long & pCANId, unsigned char & pLength, unsigned char * pData) inline
Reads a frame directly without trying again if fails
Parameters
[out] pCANId Read CAN Id
[out] pLength Read data length
[out] pData Read data
Returns
True on success, false otherwise
Definition at line 121 of file ICANConnector.h.
References Print(), and ReadImpl().
Referenced by CReadCANFrame::ReadFrom(), and WaitRead().
     {
         // Read worked ?
         if (this->ReadImpl(pCANId, pLength, pData))
         {
             #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                 // Print that we've just received a frame
                 PRINT("Received : ") ;
                 // Print frame
                 this->Print(pCANId, pLength, pData) ;
             #endif
             // Send succeeded
             return true ;
         }
         else
         {
             #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                 // Print error
                 PRINTLN("Receive failed") ;
             #endif
             // Failed !
             return false ;
         }
     }
ReadImpl()
virtual bool ICANConnector::ReadImpl (unsigned long & pCANId, unsigned char & pLength, unsigned char * pReadData) protected pure virtual
Reads a frame implementation
Parameters
[out] pCANId Message CAN Id
[out] pLength Read data length
[out] pReadData Read data
Returns
True on success, false otherwise
Implemented in CMCPCANConnector, and CDebugConnector.
Referenced by Read(), and Send().
Send()
bool ICANConnector::Send (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) inline
Sends a frame directly without trying again if fails
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Returns
True on success, false otherwise
Definition at line 189 of file ICANConnector.h.
References Print(), ReadImpl(), and SendImpl().
Referenced by WaitSend().
     {
         // Send worked ?
         if (this->SendImpl(pCANId, pLength, pData))
         {
             #ifdef ICANCONNECTOR_DEBUG_SEND
                 // Print that we've just sent a frame
                 PRINT("Sent : ") ;
                 // Print frame
                 this->Print(pCANId, pLength, pData) ;
             #endif
             // Send succeeded
             return true ;
         }
         else
         {
             #ifdef ICANCONNECTOR_DEBUG_SEND
                 // Print error
                 PRINTLN("Send failed") ;
             #endif
             // Failed !
             return false ;
         }
     }
SendImpl()
virtual bool ICANConnector::SendImpl (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) protected pure virtual
Sends a frame implementation
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Returns
True on success, false otherwise
Implemented in CDebugConnector, and CMCPCANConnector.
Referenced by Send().
SetFilter()
virtual bool ICANConnector::SetFilter (unsigned char pId, unsigned char pFrameType, unsigned long pFilter) pure virtual
Sets a specific filter
Parameters
[in] pId Filter Id
[in] pFrameType Standard or extended frame
[in] pFilter Filter to use
Returns
True on success, false otherwise
Implemented in CMCPCANConnector, and CDebugConnector.
Referenced by ~ICANConnector().
SetMask()
virtual bool ICANConnector::SetMask (unsigned char pId, unsigned char pFrameType, unsigned long pMask) pure virtual
Sets a specific mask
Parameters
[in] pId Mask Id
[in] pFrameType Standard or extended frame
[in] pMask Mask to use
Returns
True on success, false otherwise
Implemented in CMCPCANConnector, and CDebugConnector.
Referenced by ~ICANConnector().
WaitHasMessages()
bool ICANConnector::WaitHasMessages (unsigned long pTimeout = CAN_TIMEOUT) inline
Tests if there is something to read or not until time out
Parameters
[in] pTimeout Time out to use in milliseconds
Returns
True if something, false otherwise
Definition at line 55 of file ICANConnector.h.
References HasMessages().
Referenced by CReadCANFrame::ReadFrom(), and COBDFrame< ECombiBtnStatus >::SendAndUpdate().
     {
         // Get current time
         unsigned long lWaitStartTime = MILLIS() ;
         // Wait for messages
         while (!this->HasMessages())
         {
             // Reached time out ?
             if ((MILLIS() - lWaitStartTime) > pTimeout)
             {
                 // Time out ! Still no messages :
                 return false ;
             }
         }
         // Succeeded : some messages !
         return true ;
     }
WaitRead()
bool ICANConnector::WaitRead (unsigned long & pCANId, unsigned char & pLength, unsigned char * pData, unsigned long pTimeout = CAN_TIMEOUT) inline
Try to read a frame. If fails, try again until time out
Parameters
[out] pCANId Read CAN Id
[out] pLength Read data length
[out] pData Read data
[in] pTimeout Time out to use in milliseconds
Returns
True on success, false otherwise
Definition at line 89 of file ICANConnector.h.
References Read().
     {
         // Get current time
         unsigned long lWaitStartTime = MILLIS() ;
         // Wait for read to succeed
         while (!this->Read(pCANId, pLength, pData))
         {
             // Reached time out ?
             if ((MILLIS() - lWaitStartTime) > pTimeout)
             {
             #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                 // Print that we've just failed :(
                 PRINT("Receive time out !") ;
             #endif
                 // Time out !
                 return false ;
             }
         }
         // Succeeded
         return true ;
     }
WaitSend()
bool ICANConnector::WaitSend (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData, unsigned long pTimeout = CAN_TIMEOUT) inline
Try to send a frame. If fails, try again until timeout
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
[in] pTimeout Time out to use in milliseconds
Returns
True on success, false otherwise
Definition at line 157 of file ICANConnector.h.
References Send().
Referenced by CReadCANFrame::MakeAndSendFlowControlTempFrame(), and CSendCANFrame::SendTo().
     {
         // Get current time
         unsigned long lWaitStartTime = MILLIS() ;
         // Wait for send to succeed
         while (!this->Send(pCANId, pLength, pData))
         {
             // Reached time out ?
             if ((MILLIS() - lWaitStartTime) > pTimeout)
             {
             #ifdef ICANCONNECTOR_DEBUG_SEND
                 // Print that we've just failed :(
                 PRINT("Send time out !") ;
             #endif
                 // Time out !
                 return false ;
             }
         }
         // Succeeded
         return true ;
     }
The documentation for this class was generated from the following file:
C:/Users/romain.fonta/Desktop/Perso/Projet1/Projet1/CANHelperLibrary/Connector/ICANConnector.h