CANLibrary: COBDFrame< TValueType > Class Template Reference
COBDFrame< TValueType > Class Template Reference
#include "COBDFrame.h"
Public Types
typedef TValueType(* ReadFunction) (const ACANFrame &pFrame)
typedef bool(* ValidationFunction) (const ACANFrame &pFrame, const ACANFrame &pThis)
Public Member Functions
COBDFrame (unsigned long pAddress, unsigned char pD0, unsigned char pD1, unsigned char pD2, unsigned char pD3, unsigned char pD4, unsigned char pD5, unsigned char pD6, unsigned char pD7, unsigned long pReplyAddress, ValidationFunction pValidFunction, ReadFunction pReadFunction, TValueType pDefaultValue)
bool SendAndUpdate (ICANConnector &pCAN, CReadCANFrame &pReadFrame)
bool Parse (const ACANFrame &pFrame)
TValueType GetCurrentValue () const
unsigned long GetReplyAddress () const
bool IsCompatibleReply (const ACANFrame &pFrame) const
Public Member Functions inherited from CSendCANFrame
CSendCANFrame (unsigned long pAddress, unsigned char pD0=0x0, unsigned char pD1=0x0, unsigned char pD2=0x0, unsigned char pD3=0x0, unsigned char pD4=0x0, unsigned char pD5=0x0, unsigned char pD6=0x0, unsigned char pD7=0x0)
virtual unsigned char GetLength () const override
virtual unsigned long GetAddress () const override
virtual const unsigned char *const GetData () const override
bool SendTo (ICANConnector &pCAN) const
Public Member Functions inherited from ACANFrame
virtual ~ACANFrame ()
void Print () const
Protected Attributes
TValueType mCurrentValue
ReadFunction mReadFunction
ValidationFunction mValidFunction
unsigned long mReplyAddress
Protected Attributes inherited from CSendCANFrame
unsigned char mLength
unsigned long mAddress
unsigned char mData [CAN_FRAME_LENGHT]
Detailed Description
template<typename TValueType>
class COBDFrame< TValueType >
OBD frame (allows parsing of a reply) Used to simplify data creation / usage
Definition at line 14 of file COBDFrame.h.
Member Typedef Documentation
ReadFunction
template<typename TValueType> typedef TValueType(* COBDFrame< TValueType >::ReadFunction) (const ACANFrame &pFrame)
Read function declaration
Definition at line 17 of file COBDFrame.h.
ValidationFunction
template<typename TValueType> typedef bool(* COBDFrame< TValueType >::ValidationFunction) (const ACANFrame &pFrame, const ACANFrame &pThis)
Validation function declaration
Definition at line 18 of file COBDFrame.h.
Constructor & Destructor Documentation
COBDFrame()
template<typename TValueType> COBDFrame< TValueType >::COBDFrame (unsigned long pAddress, unsigned char pD0, unsigned char pD1, unsigned char pD2, unsigned char pD3, unsigned char pD4, unsigned char pD5, unsigned char pD6, unsigned char pD7, unsigned long pReplyAddress, ValidationFunction pValidFunction, ReadFunction pReadFunction, TValueType pDefaultValue) inline
Constructor
Parameters
[in] pAddress Frame address
[in] pD0 Data 0
[in] pD1 Data 1
[in] pD2 Data 2
[in] pD3 Data 3
[in] pD4 Data 4
[in] pD5 Data 5
[in] pD6 Data 6
[in] pD7 Data 7
[in] pReplyAddress Reply address to use
[in] pValidFunction Validation function to use
[in] pReadFunction Read function to use
[in] pDefaultValue Default value to use
Definition at line 37 of file COBDFrame.h.
         : CSendCANFrame(pAddress, pD0, pD1, pD2, pD3, pD4, pD5, pD6, pD7)
     {
         // Init members
         this->mReplyAddress     = pReplyAddress ;
         this->mCurrentValue     = pDefaultValue ;
         this->mReadFunction     = pReadFunction ;
         this->mValidFunction    = pValidFunction ;
     }
Member Function Documentation
GetCurrentValue()
template<typename TValueType> TValueType COBDFrame< TValueType >::GetCurrentValue () const inline
Gets current value
Returns
Current value
Definition at line 113 of file COBDFrame.h.
Referenced by FRS::CAutoDoorsLock::Update(), and FRS::COilDisplay::Update().
     {
         return this->mCurrentValue ;
     }
GetReplyAddress()
template<typename TValueType> unsigned long COBDFrame< TValueType >::GetReplyAddress () const inline
Gets reply address we are looking for
Returns
Current reply address
Definition at line 122 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::IsCompatibleReply().
     {
         return this->mReplyAddress ;
     }
IsCompatibleReply()
template<typename TValueType> bool COBDFrame< TValueType >::IsCompatibleReply (const ACANFrame & pFrame) const inline
Tests if the given frame seems to be a valid reply to the current one
Parameters
[in] pFrame Frame to test with
Returns
True if valid, false otherwise
Definition at line 132 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::Parse().
     {
         return this->mValidFunction && this->GetReplyAddress() == pFrame.GetAddress() && this->mValidFunction(pFrame, *this) ;
     }
Parse()
template<typename TValueType> bool COBDFrame< TValueType >::Parse (const ACANFrame & pFrame) inline
Try to parse some received data
Parameters
[in] pFrame Frame to use
Returns
True on success, false otherwise
Definition at line 92 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::SendAndUpdate().
     {
         // Valid function ? and given frame seems to be what we want ?
         if (this->mReadFunction && this->IsCompatibleReply(pFrame))
         {
             // Parse and get value !
             this->mCurrentValue = this->mReadFunction(pFrame) ;
             // Succeeded
             return true ;
         }
         else
         {
             return false ;
         }
     }
SendAndUpdate()
template<typename TValueType> bool COBDFrame< TValueType >::SendAndUpdate (ICANConnector & pCAN, CReadCANFrame & pReadFrame) inline
Sends data to the given CAN connector and wait for the reply. If you don't want this behavior but have a better control over the send / receive, use Send method from CSendCANFrame and the IsCompatibleReply / Parse methods provided in this class
Parameters
[in] pCAN CAN connector to use
[in] pReadFrame Read frame to use (to avoid recreating one each time in each OBD frame ...)
Returns
True on success, false otherwise
Definition at line 66 of file COBDFrame.h.
Referenced by FRS::CAutoDoorsLock::Update(), and FRS::COilDisplay::Update().
     {
         // Send succeeded ?
         if (this->SendTo(pCAN))
         {
             // Some messages received ?
             if (pCAN.WaitHasMessages())
             {
                 // And read the reply !
                 if (pReadFrame.ReadFrom(pCAN))
                 {
                     // Try to parse !
                     return this->Parse(pReadFrame) ;
                 }
             }
         }
         // Error !
         return false ;
     }
Member Data Documentation
mCurrentValue
template<typename TValueType> TValueType COBDFrame< TValueType >::mCurrentValue protected
Current value
Definition at line 138 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::COBDFrame(), COBDFrame< ECombiBtnStatus >::GetCurrentValue(), and COBDFrame< ECombiBtnStatus >::Parse().
mReadFunction
template<typename TValueType> ReadFunction COBDFrame< TValueType >::mReadFunction protected
Read function
Definition at line 139 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::COBDFrame(), and COBDFrame< ECombiBtnStatus >::Parse().
mReplyAddress
template<typename TValueType> unsigned long COBDFrame< TValueType >::mReplyAddress protected
The reply address we are looking for
Definition at line 141 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::COBDFrame(), and COBDFrame< ECombiBtnStatus >::GetReplyAddress().
mValidFunction
template<typename TValueType> ValidationFunction COBDFrame< TValueType >::mValidFunction protected
Validation function
Definition at line 140 of file COBDFrame.h.
Referenced by COBDFrame< ECombiBtnStatus >::COBDFrame(), and COBDFrame< ECombiBtnStatus >::IsCompatibleReply().
The documentation for this class was generated from the following file:
C:/Users/romain.fonta/Desktop/Perso/Projet1/Projet1/CANHelperLibrary/Frame/OBD/COBDFrame.h