CANLibrary: FRS::CSetGaugePositionFrame Class Reference
FRS::CSetGaugePositionFrame Class Reference
#include "COBDTOYOTADefines.h"
Public Member Functions
CSetGaugePositionFrame ()
bool SetPosition (EGaugeType pGauge, EGaugePosition pPosition, CAN::ICANConnector &pCAN, CAN::CReadCANFrame &pReadFrame)
Public Member Functions inherited from OBD::COBDFrame< EGaugePosition >
COBDFrame (unsigned long pAddress, unsigned char pD0, unsigned char pD1, unsigned char pD2, unsigned char pD3, unsigned char pD4, unsigned char pD5, unsigned char pD6, unsigned char pD7, unsigned long pReplyAddress, ValidationFunction pValidFunction, ReadFunction pReadFunction, EGaugePosition pDefaultValue)
bool SendAndUpdate (CAN::ICANConnector &pCAN, CAN::CReadCANFrame &pReadFrame)
bool Parse (const CAN::ACANFrame &pFrame)
EGaugePosition GetCurrentValue () const
unsigned long GetReplyAddress () const
bool IsCompatibleReply (const ACANFrame &pFrame) const
Public Member Functions inherited from CAN::CSendCANFrame
CSendCANFrame (unsigned long pAddress, unsigned char pD0=0x0, unsigned char pD1=0x0, unsigned char pD2=0x0, unsigned char pD3=0x0, unsigned char pD4=0x0, unsigned char pD5=0x0, unsigned char pD6=0x0, unsigned char pD7=0x0)
virtual unsigned char GetLength () const override
virtual unsigned long GetAddress () const override
virtual const unsigned char *const GetData () const override
bool SendTo (ICANConnector &pCAN) const
Public Member Functions inherited from CAN::ACANFrame
virtual ~ACANFrame ()
void Print () const
Static Protected Member Functions
static EGaugePosition OnParse (const ACANFrame &pFrame)
Additional Inherited Members
Public Types inherited from OBD::COBDFrame< EGaugePosition >
typedef EGaugePosition(* ReadFunction) (const CAN::ACANFrame &pFrame)
typedef bool(* ValidationFunction) (const CAN::ACANFrame &pFrame, const ACANFrame &pThis)
Protected Attributes inherited from OBD::COBDFrame< EGaugePosition >
EGaugePosition mCurrentValue
ReadFunction mReadFunction
ValidationFunction mValidFunction
unsigned long mReplyAddress
Protected Attributes inherited from CAN::CSendCANFrame
unsigned char mLength
unsigned long mAddress
unsigned char mData [CAN_FRAME_LENGHT]
Detailed Description
Sets the given gauge position
Definition at line 310 of file COBDTOYOTADefines.h.
Constructor & Destructor Documentation
CSetGaugePositionFrame()
FRS::CSetGaugePositionFrame::CSetGaugePositionFrame () inline
Constructor
Definition at line 316 of file COBDTOYOTADefines.h.
                                  : COBDFrame(0x7C0, 0x04, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x758, OBD_TOYOTA_VALIDATION, &OnParse, EGaugePosition::GP_POS_1)
         {
         }
Member Function Documentation
OnParse()
static EGaugePosition FRS::CSetGaugePositionFrame::OnParse (const ACANFrame & pFrame) inline static protected
Method called once a message is received and passed validation
Parameters
[in] pFrame Frame to parse
Returns
Parsed value
Definition at line 343 of file COBDTOYOTADefines.h.
References FRS::GP_POS_1.
         {
             // The reply only acknowledge that the query is done, so nothing to parse !
             return EGaugePosition::GP_POS_1 ;
         }
SetPosition()
bool FRS::CSetGaugePositionFrame::SetPosition (EGaugeType pGauge, EGaugePosition pPosition, CAN::ICANConnector & pCAN, CAN::CReadCANFrame & pReadFrame) inline
Tries to set the gauge position using the given CAN connector
Parameters
[in] pGauge Gauge to drive
[in] pPosition Position to set
[in] pCAN CAN connector to use
[in] pReadFrame Read frame to use (to avoid recreating one each time in each OBD frame ...)
Returns
True on success, false otherwise
Definition at line 328 of file COBDTOYOTADefines.h.
Referenced by FRS::COilDisplay::OnDisabled(), FRS::COilDisplay::OnEnabled(), and FRS::COilDisplay::UpdateImpl().
         {
             // Change the data setting first
             this->mData[2]  = static_cast<unsigned char>(pGauge) ;
             this->mData[4]  = static_cast<unsigned char>(pPosition) ;
             // Perform send
             return this->SendAndUpdate(pCAN, pReadFrame) ;
         }
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Frame/OBD/TOYOTA/COBDTOYOTADefines.h