CANLibrary: FRS::COilDisplay Class Reference
FRS::COilDisplay Class Reference
#include "COilDisplay.h"
Public Member Functions
COilDisplay (CAN::ICANConnector &pCAN, CAN::CReadCANFrame &pReadFrame)
Public Member Functions inherited from MOD::IModule
IModule (CAN::ICANConnector &pCAN, CAN::CReadCANFrame &pReadFrame, bool pEnabledByDefault, unsigned long pUpdateRate)
void Enable (unsigned long pTime)
void Disable (unsigned long pTime)
void Update (unsigned long pTime)
bool IsEnabled () const
unsigned long GetUpdateRate () const
Protected Member Functions
virtual void OnEnabled (unsigned long pTime) override
virtual void OnDisabled (unsigned long pTime) override
virtual void OnPreUpdate (unsigned long pTime) override
virtual void UpdateImpl (unsigned long pTime) override
Protected Attributes
char mCriticalWaterTemperatureThreshold
char mNormalOilTemperatureThreshold
char mWarningOilTemperatureThreshold
char mCriticalOilTemperatureThreshold
unsigned long mCombiDisplayButtonPressStart
FRS::CSetGaugePositionFrame mGaugeDriver
FRS::CQueryOilTempFrame mOilTemperature
OBD::CVehicleWaterTemperatureFrame mWaterTemperature
FRS::CQueryCombiButtonsFrame mCombiButtons
Protected Attributes inherited from MOD::IModule
CAN::ICANConnector & mCAN
CAN::CReadCANFrame & mReadFrame
Detailed Description
Manages the display of the oil temperature
Definition at line 13 of file COilDisplay.h.
Constructor & Destructor Documentation
COilDisplay()
FRS::COilDisplay::COilDisplay (CAN::ICANConnector & pCAN, CAN::CReadCANFrame & pReadFrame) inline
Constructor
Parameters
[in] pCAN CAN connector to use
[in] pReadFrame Read frame to use
Definition at line 21 of file COilDisplay.h.
References mCombiDisplayButtonPressStart, mCriticalOilTemperatureThreshold, mCriticalWaterTemperatureThreshold, mNormalOilTemperatureThreshold, and mWarningOilTemperatureThreshold.
                                                                           : IModule(pCAN, pReadFrame, false, 400)
         {
             // Init members
             this->mCombiDisplayButtonPressStart         = 0 ;
             this->mNormalOilTemperatureThreshold        = 85 ;
             this->mWarningOilTemperatureThreshold       = 110 ;
             this->mCriticalOilTemperatureThreshold      = 120 ;
             this->mCriticalWaterTemperatureThreshold    = 120 ;
         }
Member Function Documentation
OnDisabled()
virtual void FRS::COilDisplay::OnDisabled (unsigned long pTime) inline override protected virtual
Event called when the module is disabled
Parameters
[in] pTime Current time in ms
Reimplemented from MOD::IModule.
Definition at line 55 of file COilDisplay.h.
References FRS::GP_POS_1, FRS::GP_POS_8, FRS::GT_WATER, MOD::IModule::mCAN, mGaugeDriver, MOD::IModule::mReadFrame, and FRS::CSetGaugePositionFrame::SetPosition().
         {
             // Tell user by moving the temp gauge
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_8, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
         }
OnEnabled()
virtual void FRS::COilDisplay::OnEnabled (unsigned long pTime) inline override protected virtual
Event called when the module is enabled
Parameters
[in] pTime Current time in ms
Reimplemented from MOD::IModule.
Definition at line 36 of file COilDisplay.h.
References FRS::GP_POS_1, FRS::GP_POS_8, FRS::GT_WATER, MOD::IModule::mCAN, mGaugeDriver, MOD::IModule::mReadFrame, and FRS::CSetGaugePositionFrame::SetPosition().
         {
             // Tell user by moving the temp gauge
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_8, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_8, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
             this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
             DELAY(600) ;
         }
OnPreUpdate()
virtual void FRS::COilDisplay::OnPreUpdate (unsigned long pTime) inline override protected virtual
Pre-update method. Called even if not enabled
Parameters
[in] pTime Current time in ms
Reimplemented from MOD::IModule.
Definition at line 70 of file COilDisplay.h.
References MOD::IModule::Disable(), MOD::IModule::Enable(), OBD::COBDFrame< TValueType >::GetCurrentValue(), MOD::IModule::IsEnabled(), mCombiButtons, mCombiDisplayButtonPressStart, FRS::S_DISPLAY_PRESSED, and OBD::COBDFrame< TValueType >::SendAndUpdate().
         {
             // Look for activation / desactivation of the oil temperature display
             if (this->mCombiButtons.SendAndUpdate(this->mCAN, this->mReadFrame))
             {
                 // The display button is pressed ?
                 if (this->mCombiButtons.GetCurrentValue() == FRS::ECombiBtnStatus::S_DISPLAY_PRESSED)
                 {
                     // Check if elapsed time is enough to activate the display: enough ?
                     if (pTime - this->mCombiDisplayButtonPressStart > 2000)
                     {
                         // Activate or desactivate the module
                         if (this->IsEnabled())
{
                             this->Disable(pTime) ;
                         }
                         else
{
                             this->Enable(pTime) ;
                         }
                         // Reset time counter
                         this->mCombiDisplayButtonPressStart = pTime ;
                     }
                 }
                 else
                 {
                     // Reset time counter
                     this->mCombiDisplayButtonPressStart = pTime ;
                 }
             }
             else
             {
                 // Reset time counter
                 this->mCombiDisplayButtonPressStart = pTime ;
             }
         }
UpdateImpl()
virtual void FRS::COilDisplay::UpdateImpl (unsigned long pTime) inline override protected virtual
Update method implementation
Parameters
[in] pTime Current time in ms
Implements MOD::IModule.
Definition at line 112 of file COilDisplay.h.
References OBD::COBDFrame< TValueType >::GetCurrentValue(), FRS::GP_POS_1, FRS::GP_POS_7, FRS::GP_POS_8, FRS::GT_WATER, MOD::IModule::mCAN, mCriticalOilTemperatureThreshold, mCriticalWaterTemperatureThreshold, mGaugeDriver, mNormalOilTemperatureThreshold, mOilTemperature, MOD::IModule::mReadFrame, mWarningOilTemperatureThreshold, mWaterTemperature, OBD::COBDFrame< TValueType >::SendAndUpdate(), and FRS::CSetGaugePositionFrame::SetPosition().
         {
         #ifdef DEBUG_MODULES
             // Print that we are updating the module
             PRINTLN("Updating oil display module") ;
         #endif
             // Query water / oil temperatures succeeded ?
             if (this->mWaterTemperature.SendAndUpdate(this->mCAN, this->mReadFrame) && this->mOilTemperature.SendAndUpdate(this->mCAN, this->mReadFrame))
             {
                 // Water temperature is correct ?
                 if (this->mWaterTemperature.GetCurrentValue() < mCriticalWaterTemperatureThreshold)
                 {
                     // Oil too hot ?
                     if (this->mOilTemperature.GetCurrentValue() >= this->mCriticalOilTemperatureThreshold)
                     {
                         this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_8, this->mCAN, this->mReadFrame) ;
                     }
                     // Oil almost too hot ?
                     else if (this->mOilTemperature.GetCurrentValue() >= this->mWarningOilTemperatureThreshold)
                     {
                         this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_7, this->mCAN, this->mReadFrame) ;
                     }
                     // Oil normal ?
                     else if (this->mOilTemperature.GetCurrentValue() >= this->mNormalOilTemperatureThreshold)
                     {
                         // Let the water informations take the control of the gauge
                     }
                     // Oil cold ?
                     else
                     {
                         this->mGaugeDriver.SetPosition(FRS::EGaugeType::GT_WATER, FRS::EGaugePosition::GP_POS_1, this->mCAN, this->mReadFrame) ;
                     }
                 }
                 else
                 {
                     // Water temperature too hot ! Stop displaying oil one, this is an emergency
                 }
             }
         }
Member Data Documentation
mCombiButtons
FRS::CQueryCombiButtonsFrame FRS::COilDisplay::mCombiButtons protected
Frame to query combi buttons status
Definition at line 162 of file COilDisplay.h.
Referenced by OnPreUpdate().
mCombiDisplayButtonPressStart
unsigned long FRS::COilDisplay::mCombiDisplayButtonPressStart protected
Time when the user started to press the cluster display button
Definition at line 158 of file COilDisplay.h.
Referenced by COilDisplay(), and OnPreUpdate().
mCriticalOilTemperatureThreshold
char FRS::COilDisplay::mCriticalOilTemperatureThreshold protected
Above this value oil is in critical temperature range (in degrees)
Definition at line 157 of file COilDisplay.h.
Referenced by COilDisplay(), and UpdateImpl().
mCriticalWaterTemperatureThreshold
char FRS::COilDisplay::mCriticalWaterTemperatureThreshold protected
Critical water temprature after which oil display is disabled (emergency)
Definition at line 154 of file COilDisplay.h.
Referenced by COilDisplay(), and UpdateImpl().
mGaugeDriver
FRS::CSetGaugePositionFrame FRS::COilDisplay::mGaugeDriver protected
Frame to drive the cluster gauges
Definition at line 159 of file COilDisplay.h.
Referenced by OnDisabled(), OnEnabled(), and UpdateImpl().
mNormalOilTemperatureThreshold
char FRS::COilDisplay::mNormalOilTemperatureThreshold protected
Above this value oil is in normal temperature range (in degrees)
Definition at line 155 of file COilDisplay.h.
Referenced by COilDisplay(), and UpdateImpl().
mOilTemperature
FRS::CQueryOilTempFrame FRS::COilDisplay::mOilTemperature protected
Query the current oil temperature
Definition at line 160 of file COilDisplay.h.
Referenced by UpdateImpl().
mWarningOilTemperatureThreshold
char FRS::COilDisplay::mWarningOilTemperatureThreshold protected
Above this value oil is in warning temperature range (in degrees)
Definition at line 156 of file COilDisplay.h.
Referenced by COilDisplay(), and UpdateImpl().
mWaterTemperature
OBD::CVehicleWaterTemperatureFrame FRS::COilDisplay::mWaterTemperature protected
Query the current water temperature
Definition at line 161 of file COilDisplay.h.
Referenced by UpdateImpl().
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Modules/TOYOTA/FRS/COilDisplay.h