CANLibrary: CAN::CReadCANFrame Class Reference
CAN::CReadCANFrame Class Reference
#include "CReadCANFrame.h"
Public Member Functions
CReadCANFrame ()
virtual unsigned char GetLength () const override
virtual unsigned long GetAddress () const override
virtual const unsigned char *const GetData () const override
bool ReadFrom (ICANConnector &pCAN)
Public Member Functions inherited from CAN::ACANFrame
virtual ~ACANFrame ()
void Print () const
Protected Member Functions
void Clean ()
bool MakeAndSendFlowControlTempFrame (unsigned long pOriginalAddress, ICANConnector &pCAN)
Protected Attributes
unsigned char mLength
unsigned long mAddress
unsigned char mData [CAN_MULTI_FRAME_MAX_LENGHT]
unsigned char mTempLength
unsigned long mTempAddress
unsigned char mTempData [CAN_FRAME_LENGHT]
Detailed Description
A frame used to read CAN data
Definition at line 27 of file CReadCANFrame.h.
Constructor & Destructor Documentation
CReadCANFrame()
CAN::CReadCANFrame::CReadCANFrame () inline
Constructor
Definition at line 33 of file CReadCANFrame.h.
References Clean().
         {
             // Init members
             this->Clean() ;
         }
Member Function Documentation
Clean()
void CAN::CReadCANFrame::Clean () inline protected
Cleans the object
Definition at line 213 of file CReadCANFrame.h.
References mAddress, and mLength.
Referenced by CReadCANFrame(), and ReadFrom().
         {
             this->mLength   = 0 ;
             this->mAddress  = 0 ;
         }
GetAddress()
virtual unsigned long CAN::CReadCANFrame::GetAddress () const inline override virtual
Gets frame address
Returns
Current frame address
Implements CAN::ACANFrame.
Definition at line 52 of file CReadCANFrame.h.
References mAddress.
         {
             return this->mAddress ;
         }
GetData()
virtual const unsigned char* const CAN::CReadCANFrame::GetData () const inline override virtual
Gets data
Returns
Current data
Implements CAN::ACANFrame.
Definition at line 61 of file CReadCANFrame.h.
References mData.
         {
             return this->mData ;
         }
GetLength()
virtual unsigned char CAN::CReadCANFrame::GetLength () const inline override virtual
Gets data length
Returns
Current data length
Implements CAN::ACANFrame.
Definition at line 43 of file CReadCANFrame.h.
References mLength.
         {
             return this->mLength ;
         }
MakeAndSendFlowControlTempFrame()
bool CAN::CReadCANFrame::MakeAndSendFlowControlTempFrame (unsigned long pOriginalAddress, ICANConnector & pCAN) inline protected
Makes a flow control frame and sends it
Parameters
[in] pOriginalAddress First frame original address
[in] pCAN CAN connector to use
Returns
True on sucess, false otherwise
Definition at line 225 of file CReadCANFrame.h.
References mAddress, mTempAddress, mTempData, mTempLength, and CAN::ICANConnector::WaitSend().
Referenced by ReadFrom().
         {
             // Define address and length
             this->mTempAddress  = pOriginalAddress - CAN_FLOW_CONTROL_ADDRESS_VALUE ;
             this->mTempLength   = CAN_FRAME_LENGHT ;
             // Define data
             this->mTempData[0]  = CAN_FLOW_FRAME_ID << 4 ;  // Flow control identifier
             this->mTempData[1]  = 0x01 ;                    // We want the CAN bus to sends us one consecutive frame only
             this->mTempData[2]  = CAN_NO_DATA ;
             this->mTempData[3]  = CAN_NO_DATA ;
             this->mTempData[4]  = CAN_NO_DATA ;
             this->mTempData[5]  = CAN_NO_DATA ;
             this->mTempData[6]  = CAN_NO_DATA ;
             this->mTempData[7]  = CAN_NO_DATA ;
             // Send our flow request using the correct address and wait until send works or time out
             return pCAN.WaitSend(this->mAddress - CAN_FLOW_CONTROL_ADDRESS_VALUE, CAN_FRAME_LENGHT, this->mTempData) ;
         }
ReadFrom()
bool CAN::CReadCANFrame::ReadFrom (ICANConnector & pCAN) inline
Reads data from the given reader
Parameters
[in] pCAN CAN connector to use
Returns
True on success, false otherwise
Definition at line 71 of file CReadCANFrame.h.
References Clean(), mAddress, MakeAndSendFlowControlTempFrame(), mData, mLength, mTempAddress, mTempData, mTempLength, CAN::ACANFrame::Print(), CAN::ICANConnector::Read(), and CAN::ICANConnector::WaitHasMessages().
Referenced by OBD::COBDFrame< ECombiBtnStatus >::SendAndUpdate().
         {
             // A message available ?
             if (pCAN.WaitHasMessages())
             {
                 // Read succeed ?
                 if (pCAN.Read(this->mTempAddress, this->mTempLength, this->mTempData))
                 {
                     // Did we just read a single frame ?
                     if (CANIsSingleFrame(this->mTempData[0]))
                     {
                         // For each data received in temp buffer
                         for (int lDataIndex = 0 ; lDataIndex < this->mTempLength ; lDataIndex++)
{
                             // Copy data over correct buffer
                             this->mData[lDataIndex] = this->mTempData[lDataIndex] ;
                         }
                         // And get correct length and address
                         this->mLength   = this->mTempLength ;
                         this->mAddress  = this->mTempAddress ;
                         // Nothing more to do, it's perfect !
                         return true ;
                     }
                     // A first frame ?
                     else if (CANIsFirstFrame(this->mTempData[0]))
                     {
                         // Extract data from the first frame
{
                             // Extract the lenght and store the address
                             this->mLength   = (((unsigned short)(this->mTempData[0] & 0x0F)) << 8) + this->mTempData[1] ;
                             this->mAddress  = this->mTempAddress ;
                             // For each data received in temp buffer skipping first byte (first frame ID)
                             for (int lDataIndex = 1 ; lDataIndex < this->mTempLength ; lDataIndex++)
{
                                 // Copy data over correct buffer
                                 this->mData[lDataIndex - 1] = this->mTempData[lDataIndex] ;
                             }
                         }
                         // We now have to ask CAN bus to send us the remaining data
                         // Store current index position to append correctly next replies
                         unsigned short lCurrentIndex = 4 ;  // First frame is 4 data (8 - 2 (First frame / lenght ID) - 2 (Mode and Pid))
                         // While we haven't read all the data
                         while (lCurrentIndex < this->mLength)
{
                             // Make and send flow control succeeded ?
                             if (this->MakeAndSendFlowControlTempFrame(this->mAddress, pCAN))
{
                                 // Wait for at least a reply
                                 if (pCAN.WaitHasMessages())
{
                                     // And now, parse the consecutive frames we might have received
                                     pCAN.Read(this->mTempAddress, this->mTempLength, this->mTempData) ;
                                     // A consecutive frame ?
                                     if (CANIsConsecutiveFrame(this->mTempData[0]))
{
                                         // For each data received in temp buffer skipping first byte (consecutive frame ID)
                                         for (int lDataIndex = 1 ; lDataIndex < this->mTempLength ; lDataIndex++)
{
                                             // Copy data over correct buffer
                                             this->mData[lDataIndex - 1 + lCurrentIndex] = this->mTempData[lDataIndex] ;
                                         }
                                         // Increment current index with read data
                                         lCurrentIndex += 7 ;    // Consecutive frame is 7 data (8 - consecutive frame ID)
                                     }
                                     // Error : not a consecutive frame !
                                     else
{
                                         // Clean
                                         this->Clean() ;
                                         // Leave
                                         return false ;
                                     }
                                 }
                                 // Reply timeout
                                 else
{
                                     return false ;
                                 }
                             }
                             // Send timeout
                             else
{
                                 return false ;
                             }
                         }
                         #ifdef CREADCANFRAME_DEBUG_RECEIVE
                             // Print debug
                             this->Print() ;
                         #endif
                         // Seems ok
                         return true ;
                     }
                     // Unknow message
                     else
                     {
                         // For each data received in temp buffer
                         for (int lDataIndex = 0 ; lDataIndex < this->mTempLength ; lDataIndex++)
{
                             // Copy data over correct buffer
                             this->mData[lDataIndex] = this->mTempData[lDataIndex] ;
                         }
                         // And get correct length and address
                         this->mLength   = this->mTempLength ;
                         this->mAddress  = this->mTempAddress ;
                         #ifdef CREADCANFRAME_DEBUG_RECEIVE
                             // Print debug
                             PRINT_STR("Received a specific frame type which is not standard :") ;
                             PRINTLNHEX(this->mData[0] & 0xF0) ;
                         #endif
                         // Specific frame type which is non standard
                         return true ;
                     }
                 }
                 else
                 {
                     // Read failed
                     return false ;
                 }
             }
             else
             {
                 // No messages
                 return false ;
             }
         }
Member Data Documentation
mAddress
unsigned long CAN::CReadCANFrame::mAddress protected
Frame address
Definition at line 247 of file CReadCANFrame.h.
Referenced by Clean(), GetAddress(), MakeAndSendFlowControlTempFrame(), and ReadFrom().
mData
unsigned char CAN::CReadCANFrame::mData[CAN_MULTI_FRAME_MAX_LENGHT] protected
Data values
Definition at line 248 of file CReadCANFrame.h.
Referenced by GetData(), and ReadFrom().
mLength
unsigned char CAN::CReadCANFrame::mLength protected
Data length
Definition at line 246 of file CReadCANFrame.h.
Referenced by Clean(), GetLength(), and ReadFrom().
mTempAddress
unsigned long CAN::CReadCANFrame::mTempAddress protected
Temporary frame address
Definition at line 250 of file CReadCANFrame.h.
Referenced by MakeAndSendFlowControlTempFrame(), and ReadFrom().
mTempData
unsigned char CAN::CReadCANFrame::mTempData[CAN_FRAME_LENGHT] protected
Temporary data values
Definition at line 251 of file CReadCANFrame.h.
Referenced by MakeAndSendFlowControlTempFrame(), and ReadFrom().
mTempLength
unsigned char CAN::CReadCANFrame::mTempLength protected
Temporary data length
Definition at line 249 of file CReadCANFrame.h.
Referenced by MakeAndSendFlowControlTempFrame(), and ReadFrom().
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Frame/CAN/CReadCANFrame.h