CANLibrary: CAN::ACANFrame Class Reference
CAN::ACANFrame Class Reference abstract
#include "ACANFrame.h"
Public Member Functions
virtual ~ACANFrame ()
virtual unsigned char GetLength () const =0
virtual unsigned long GetAddress () const =0
virtual const unsigned char *const GetData () const =0
void Print () const
Detailed Description
Base CAN frame class
Definition at line 17 of file ACANFrame.h.
Constructor & Destructor Documentation
~ACANFrame()
virtual CAN::ACANFrame::~ACANFrame () inline virtual
Destructor
Definition at line 23 of file ACANFrame.h.
References GetAddress(), GetData(), and GetLength().
         {
         }
Member Function Documentation
GetAddress()
virtual unsigned long CAN::ACANFrame::GetAddress () const pure virtual
Gets frame address
Returns
Current frame address
Implemented in CAN::CSendCANFrame, and CAN::CReadCANFrame.
Referenced by Print(), and ~ACANFrame().
GetData()
virtual const unsigned char* const CAN::ACANFrame::GetData () const pure virtual
Gets data
Returns
Current data
Implemented in CAN::CSendCANFrame, and CAN::CReadCANFrame.
Referenced by Print(), and ~ACANFrame().
GetLength()
virtual unsigned char CAN::ACANFrame::GetLength () const pure virtual
Gets data length
Returns
Current data length
Implemented in CAN::CSendCANFrame, and CAN::CReadCANFrame.
Referenced by Print(), and ~ACANFrame().
Print()
void CAN::ACANFrame::Print () const inline
Prints the class content
Definition at line 48 of file ACANFrame.h.
References GetAddress(), GetData(), and GetLength().
Referenced by CAN::CReadCANFrame::ReadFrom().
         {
             // Print address first
             PRINT("0x") ;
             PRINTHEX(this->GetAddress()) ;
             PRINT("\t") ;
             // Then each data
             for (int lDataIndex = 0 ; lDataIndex < this->GetLength() ; lDataIndex++)
             {
                 PRINT(this->GetData()[lDataIndex] <= 0xF ? " 0x0" : " 0x") ;
                 PRINTHEX(this->GetData()[lDataIndex]) ;
             }
             // And go next line
             PRINTLN("") ;
         }
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Frame/CAN/ACANFrame.h