CANLibrary: MOD::IModule Class Reference
MOD::IModule Class Reference abstract
#include "IModule.h"
Public Member Functions
IModule (CAN::ICANConnector &pCAN, CAN::CReadCANFrame &pReadFrame, bool pEnabledByDefault, unsigned long pUpdateRate)
void Enable (unsigned long pTime)
void Disable (unsigned long pTime)
void Update (unsigned long pTime)
bool IsEnabled () const
unsigned long GetUpdateRate () const
Protected Member Functions
virtual void OnEnabled (unsigned long pTime)
virtual void OnDisabled (unsigned long pTime)
virtual void OnPreUpdate (unsigned long pTime)
virtual void UpdateImpl (unsigned long pTime)=0
Protected Attributes
CAN::ICANConnector & mCAN
CAN::CReadCANFrame & mReadFrame
Private Attributes
bool mEnabled
unsigned long mUpdateRate
unsigned long mLastUpdateTime
Detailed Description
Base class for modules
Definition at line 13 of file IModule.h.
Constructor & Destructor Documentation
IModule()
MOD::IModule::IModule (CAN::ICANConnector & pCAN, CAN::CReadCANFrame & pReadFrame, bool pEnabledByDefault, unsigned long pUpdateRate) inline
Constructor
Parameters
[in] pCAN CAN connector to use
[in] pReadFrame Read frame to use
[in] pEnabledByDefault If the module is enabled by default
[in] pUpdateRate Wanted update rate
Definition at line 23 of file IModule.h.
References mEnabled, mLastUpdateTime, and mUpdateRate.
          : mCAN(pCAN), mReadFrame(pReadFrame)
         {
             // Init members
             this->mLastUpdateTime   = 0 ;
             this->mUpdateRate       = pUpdateRate ;
             this->mEnabled          = pEnabledByDefault ;
         }
Member Function Documentation
Disable()
void MOD::IModule::Disable (unsigned long pTime) inline
Disable the module
Parameters
[in] pTime Current time in ms
Definition at line 49 of file IModule.h.
References mEnabled, and OnDisabled().
Referenced by FRS::COilDisplay::OnPreUpdate().
         {
             // Now disabled
             this->mEnabled = false ;
             // Call event
             this->OnDisabled(pTime) ;
         }
Enable()
void MOD::IModule::Enable (unsigned long pTime) inline
Enable the module
Parameters
[in] pTime Current time in ms
Definition at line 36 of file IModule.h.
References mEnabled, and OnEnabled().
Referenced by FRS::COilDisplay::OnPreUpdate().
         {
             // Now enabled
             this->mEnabled = true ;
             // Call event
             this->OnEnabled(pTime) ;
         }
GetUpdateRate()
unsigned long MOD::IModule::GetUpdateRate () const inline
Gets current update rate
Returns
Current update rate
Definition at line 95 of file IModule.h.
References mUpdateRate.
Referenced by Update().
         {
             return this->mUpdateRate ;
         }
IsEnabled()
bool MOD::IModule::IsEnabled () const inline
Tells whether the module is enabled or not
Returns
Current status
Definition at line 86 of file IModule.h.
References mEnabled.
Referenced by FRS::COilDisplay::OnPreUpdate(), and Update().
         {
             return this->mEnabled ;
         }
OnDisabled()
virtual void MOD::IModule::OnDisabled (unsigned long pTime) inline protected virtual
Event called when the module is disabled
Parameters
[in] pTime Current time in ms
Reimplemented in FRS::COilDisplay.
Definition at line 113 of file IModule.h.
Referenced by Disable().
         {
         }
OnEnabled()
virtual void MOD::IModule::OnEnabled (unsigned long pTime) inline protected virtual
Event called when the module is enabled
Parameters
[in] pTime Current time in ms
Reimplemented in FRS::COilDisplay.
Definition at line 105 of file IModule.h.
Referenced by Enable().
         {
         }
OnPreUpdate()
virtual void MOD::IModule::OnPreUpdate (unsigned long pTime) inline protected virtual
Pre-update method. Called even if not enabled
Parameters
[in] pTime Current time in ms
Reimplemented in FRS::COilDisplay.
Definition at line 121 of file IModule.h.
References UpdateImpl().
Referenced by Update().
         {
         }
Update()
void MOD::IModule::Update (unsigned long pTime) inline
Update method (to call each frame)
Parameters
[in] pTime Current time in ms
Definition at line 62 of file IModule.h.
References GetUpdateRate(), IsEnabled(), mLastUpdateTime, OnPreUpdate(), and UpdateImpl().
         {
             // Method called even if not enabled
             this->OnPreUpdate(pTime) ;
             // Enabled ?
             if (this->IsEnabled())
             {
                 // Update rate reached ?
                 if ((unsigned long)(pTime - this->mLastUpdateTime) >= this->GetUpdateRate())
                 {
                     // Now updated
                     this->mLastUpdateTime = pTime ;
                     // Call implementation
                     this->UpdateImpl(pTime) ;
                 }
             }
         }
UpdateImpl()
virtual void MOD::IModule::UpdateImpl (unsigned long pTime) protected pure virtual
Update method implementation
Parameters
[in] pTime Current time in ms
Implemented in FRS::COilDisplay, and FRS::CCloseDoors.
Referenced by OnPreUpdate(), and Update().
Member Data Documentation
mCAN
CAN::ICANConnector& MOD::IModule::mCAN protected
Current connector
Definition at line 132 of file IModule.h.
Referenced by FRS::COilDisplay::OnDisabled(), FRS::COilDisplay::OnEnabled(), FRS::CCloseDoors::UpdateImpl(), and FRS::COilDisplay::UpdateImpl().
mEnabled
bool MOD::IModule::mEnabled private
If the module is enabled or not
Definition at line 136 of file IModule.h.
Referenced by Disable(), Enable(), IModule(), and IsEnabled().
mLastUpdateTime
unsigned long MOD::IModule::mLastUpdateTime private
Last update time
Definition at line 138 of file IModule.h.
Referenced by IModule(), and Update().
mReadFrame
CAN::CReadCANFrame& MOD::IModule::mReadFrame protected
Current read frame
Definition at line 133 of file IModule.h.
Referenced by FRS::COilDisplay::OnDisabled(), FRS::COilDisplay::OnEnabled(), FRS::CCloseDoors::UpdateImpl(), and FRS::COilDisplay::UpdateImpl().
mUpdateRate
unsigned long MOD::IModule::mUpdateRate private
Current update rate
Definition at line 137 of file IModule.h.
Referenced by GetUpdateRate(), and IModule().
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Modules/IModule.h