CANLibrary: ACANFrame Class Reference
ACANFrame Class Reference abstract
#include "ACANFrame.h"
Public Member Functions
virtual ~ACANFrame ()
virtual unsigned char GetLength () const =0
virtual unsigned long GetAddress () const =0
virtual const unsigned char *const GetData () const =0
void Print () const
Detailed Description
Base CAN frame class
Definition at line 11 of file ACANFrame.h.
Constructor & Destructor Documentation
~ACANFrame()
virtual ACANFrame::~ACANFrame () inline virtual
Destructor
Definition at line 17 of file ACANFrame.h.
References GetAddress(), GetData(), and GetLength().
     {
     }
Member Function Documentation
GetAddress()
virtual unsigned long ACANFrame::GetAddress () const pure virtual
Gets frame address
Returns
Current frame address
Implemented in CSendCANFrame, and CReadCANFrame.
Referenced by COBDFrame< ECombiBtnStatus >::IsCompatibleReply(), Print(), and ~ACANFrame().
GetData()
virtual const unsigned char* const ACANFrame::GetData () const pure virtual
Gets data
Returns
Current data
Implemented in CSendCANFrame, and CReadCANFrame.
Referenced by OBD::CEngineRPMFrame::OnParse(), FRS::CFRSQueryCombiButtonsFrame::OnParse(), OBD::CVehicleSpeedFrame::OnParse(), FRS::CFRSQueryOilTempFrame::OnParse(), OBD::CVehicleWaterTemperatureFrame::OnParse(), FRS::CFRSQueryDriverDoorsLockFrame::OnParse(), FRS::CFRSQueryPassengerDoorsLockFrame::OnParse(), FRS::CFRSQueryElecPowerFrame::OnParse(), Print(), and ~ACANFrame().
GetLength()
virtual unsigned char ACANFrame::GetLength () const pure virtual
Gets data length
Returns
Current data length
Implemented in CSendCANFrame, and CReadCANFrame.
Referenced by Print(), and ~ACANFrame().
Print()
void ACANFrame::Print () const inline
Prints the class content
Definition at line 42 of file ACANFrame.h.
References GetAddress(), GetData(), and GetLength().
Referenced by CReadCANFrame::ReadFrom().
     {
         // Print address first
         PRINT("0x") ;
         PRINTHEX(this->GetAddress()) ;
         PRINT("\t") ;
         // Then each data
         for (int lDataIndex = 0 ; lDataIndex < this->GetLength() ; lDataIndex++)
         {
             PRINT(this->GetData()[lDataIndex] <= 0xF ? " 0x0" : " 0x") ;
             PRINTHEX(this->GetData()[lDataIndex]) ;
         }
         // And go next line
         PRINTLN("") ;
     }
The documentation for this class was generated from the following file:
C:/Users/romain.fonta/Desktop/Perso/Projet1/Projet1/CANHelperLibrary/Frame/CAN/ACANFrame.h