CANLibrary: CAN::ICANConnector Class Reference
CAN::ICANConnector Class Reference abstract
#include "ICANConnector.h"
Public Member Functions
virtual bool Initialize (SetupFiltersAndMasks pSetupFunc=nullptr)=0
virtual bool Close ()=0
virtual bool HasError ()=0
virtual char GetError ()=0
virtual bool SetMask (unsigned char pId, unsigned char pFrameType, unsigned long pMask)=0
virtual bool SetFilter (unsigned char pId, unsigned char pFrameType, unsigned long pFilter)=0
bool WaitHasMessages (unsigned long pTimeout=CAN_TIMEOUT)
virtual bool HasMessages ()=0
bool WaitRead (unsigned long &pCANId, unsigned char &pLength, unsigned char *pData, unsigned long pTimeout=CAN_TIMEOUT)
bool Read (unsigned long &pCANId, unsigned char &pLength, unsigned char *pData)
bool WaitSend (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData, unsigned long pTimeout=CAN_TIMEOUT)
bool Send (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData)
Protected Member Functions
virtual ~ICANConnector ()
virtual bool ReadImpl (unsigned long &pCANId, unsigned char &pLength, unsigned char *pReadData)=0
virtual bool SendImpl (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData)=0
void Print (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) const
Detailed Description
Interface through CAN library
Definition at line 37 of file ICANConnector.h.
Constructor & Destructor Documentation
~ICANConnector()
virtual CAN::ICANConnector::~ICANConnector () inline protected virtual
Destructor
Definition at line 43 of file ICANConnector.h.
References Close(), GetError(), HasError(), Initialize(), SetFilter(), and SetMask().
         {
         }
Member Function Documentation
Close()
virtual bool CAN::ICANConnector::Close () pure virtual
Closes connector
Returns
True on success, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by ~ICANConnector().
GetError()
virtual char CAN::ICANConnector::GetError () pure virtual
Gets the current error code if any
Returns
Current error code
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by ~ICANConnector().
HasError()
virtual bool CAN::ICANConnector::HasError () pure virtual
Tests whether there is some errors on the connector or not (configuration, etc.)
Returns
True if some errors, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by CAN::InitializeCAN(), and ~ICANConnector().
HasMessages()
virtual bool CAN::ICANConnector::HasMessages () pure virtual
Tests if there is something to read or not
Returns
True if something, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by CAN::InitializeCAN(), and WaitHasMessages().
Initialize()
virtual bool CAN::ICANConnector::Initialize (SetupFiltersAndMasks pSetupFunc = nullptr) pure virtual
Initialize the CAN bus
Parameters
[in] pSetupFunc Setup function to use
Returns
True on success, false otherwise
Implemented in CAN::CMCPCANConnector.
Referenced by CAN::InitializeCAN(), and ~ICANConnector().
Print()
void CAN::ICANConnector::Print (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) const inline protected
Prints the frame content
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Definition at line 296 of file ICANConnector.h.
Referenced by Read(), and Send().
         {
             // Print address first
             PRINT_STR("0x") ;
             PRINTHEX(pCANId) ;
             PRINT_STR("\t") ;
             // Then each data
             for (int lDataIndex = 0 ; lDataIndex < pLength ; lDataIndex++)
             {
                 PRINT(pData[lDataIndex] <= 0xF ? " 0x0" : " 0x") ;
                 PRINTHEX(pData[lDataIndex]) ;
             }
             // And go next line
             PRINTLN_STR("") ;
         }
Read()
bool CAN::ICANConnector::Read (unsigned long & pCANId, unsigned char & pLength, unsigned char * pData) inline
Reads a frame directly without trying again if fails
Parameters
[out] pCANId Read CAN Id
[out] pLength Read data length
[out] pData Read data
Returns
True on success, false otherwise
Definition at line 162 of file ICANConnector.h.
References Print(), and ReadImpl().
Referenced by CAN::InitializeCAN(), CAN::CReadCANFrame::ReadFrom(), and WaitRead().
         {
             // Read worked ?
             if (this->ReadImpl(pCANId, pLength, pData))
             {
                 #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                     // Print current time
                     PRINT(MILLIS()) ;
                     // Print that we've just received a frame
                     PRINT_STR(" Received: ") ;
                     // Print frame
                     this->Print(pCANId, pLength, pData) ;
                 #endif
                 // Send succeeded
                 return true ;
             }
             else
             {
                 #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                     // Print error
                     PRINTLN_STR("Receive failed") ;
                 #endif
                 // Failed !
                 return false ;
             }
         }
ReadImpl()
virtual bool CAN::ICANConnector::ReadImpl (unsigned long & pCANId, unsigned char & pLength, unsigned char * pReadData) protected pure virtual
Reads a frame implementation
Parameters
[out] pCANId Message CAN Id
[out] pLength Read data length
[out] pReadData Read data
Returns
True on success, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by Read(), and Send().
Send()
bool CAN::ICANConnector::Send (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) inline
Sends a frame directly without trying again if fails
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Returns
True on success, false otherwise
Definition at line 233 of file ICANConnector.h.
References Print(), ReadImpl(), and SendImpl().
Referenced by WaitSend().
         {
             // Send worked ?
             if (this->SendImpl(pCANId, pLength, pData))
             {
                 #ifdef ICANCONNECTOR_DEBUG_SEND
                     // Print current time
                     PRINT(MILLIS()) ;
                     // Print that we've just sent a frame
                     PRINT_STR(" Sent: ") ;
                     // Print frame
                     this->Print(pCANId, pLength, pData) ;
                 #endif
                 // Send succeeded
                 return true ;
             }
             else
             {
                 #ifdef ICANCONNECTOR_DEBUG_SEND
                     // Print current time
                     PRINT(MILLIS()) ;
                     // Print error
                     PRINT_STR(" Send failed: ") ;
                     // Print frame
                     this->Print(pCANId, pLength, pData) ;
                 #endif
                 // Failed !
                 return false ;
             }
         }
SendImpl()
virtual bool CAN::ICANConnector::SendImpl (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData) protected pure virtual
Sends a frame implementation
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
Returns
True on success, false otherwise
Implemented in DEBUG::CDebugConnector, and CAN::CMCPCANConnector.
Referenced by Send().
SetFilter()
virtual bool CAN::ICANConnector::SetFilter (unsigned char pId, unsigned char pFrameType, unsigned long pFilter) pure virtual
Sets a specific filter
Parameters
[in] pId Filter Id
[in] pFrameType Standard or extended frame
[in] pFilter Filter to use
Returns
True on success, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by FRS::FiltersAndMasksConfiguration(), and ~ICANConnector().
SetMask()
virtual bool CAN::ICANConnector::SetMask (unsigned char pId, unsigned char pFrameType, unsigned long pMask) pure virtual
Sets a specific mask
Parameters
[in] pId Mask Id
[in] pFrameType Standard or extended frame
[in] pMask Mask to use
Returns
True on success, false otherwise
Implemented in CAN::CMCPCANConnector, and DEBUG::CDebugConnector.
Referenced by FRS::FiltersAndMasksConfiguration(), and ~ICANConnector().
WaitHasMessages()
bool CAN::ICANConnector::WaitHasMessages (unsigned long pTimeout = CAN_TIMEOUT) inline
Tests if there is something to read or not until time out
Parameters
[in] pTimeout Time out to use in milliseconds
Returns
True if something, false otherwise
Definition at line 96 of file ICANConnector.h.
References HasMessages().
Referenced by CAN::CReadCANFrame::ReadFrom(), and OBD::COBDFrame< ECombiBtnStatus >::SendAndUpdate().
         {
             // Get current time
             unsigned long lWaitStartTime = MILLIS() ;
             // Wait for messages
             while (!this->HasMessages())
             {
                 // Reached time out ?
                 if ((MILLIS() - lWaitStartTime) > pTimeout)
                 {
                     // Time out ! Still no messages :
                     return false ;
                 }
             }
             // Succeeded : some messages !
             return true ;
         }
WaitRead()
bool CAN::ICANConnector::WaitRead (unsigned long & pCANId, unsigned char & pLength, unsigned char * pData, unsigned long pTimeout = CAN_TIMEOUT) inline
Try to read a frame. If fails, try again until time out
Parameters
[out] pCANId Read CAN Id
[out] pLength Read data length
[out] pData Read data
[in] pTimeout Time out to use in milliseconds
Returns
True on success, false otherwise
Definition at line 130 of file ICANConnector.h.
References Read().
         {
             // Get current time
             unsigned long lWaitStartTime = MILLIS() ;
             // Wait for read to succeed
             while (!this->Read(pCANId, pLength, pData))
             {
                 // Reached time out ?
                 if ((MILLIS() - lWaitStartTime) > pTimeout)
                 {
                     #ifdef ICANCONNECTOR_DEBUG_RECEIVE
                         // Print that we've just failed :(
                         PRINTLN_STR("Receive time out !") ;
                     #endif
                     // Time out !
                     return false ;
                 }
             }
             // Succeeded
             return true ;
         }
WaitSend()
bool CAN::ICANConnector::WaitSend (unsigned long pCANId, unsigned char pLength, const unsigned char *const pData, unsigned long pTimeout = CAN_TIMEOUT) inline
Try to send a frame. If fails, try again until timeout
Parameters
[in] pCANId CAN Id to use
[in] pLength Data length
[in] pData Data to send
[in] pTimeout Time out to use in milliseconds
Returns
True on success, false otherwise
Definition at line 201 of file ICANConnector.h.
References Send().
Referenced by CAN::CReadCANFrame::MakeAndSendFlowControlTempFrame(), and CAN::CSendCANFrame::SendTo().
         {
             // Get current time
             unsigned long lWaitStartTime = MILLIS() ;
             // Wait for send to succeed
             while (!this->Send(pCANId, pLength, pData))
             {
                 // Reached time out ?
                 if ((MILLIS() - lWaitStartTime) > pTimeout)
                 {
                     #ifdef ICANCONNECTOR_DEBUG_SEND
                         // Print that we've just failed :(
                         PRINTLN_STR("Send time out !") ;
                     #endif
                     // Time out !
                     return false ;
                 }
             }
             // Succeeded
             return true ;
         }
The documentation for this class was generated from the following file:
C:/Users/admin-lcai/Desktop/Arduino/Projet/ArduinoCANHelperLibrary/CANHelperLibrary/Connector/ICANConnector.h