CANLibrary: CAN Namespace Reference
CAN Namespace Reference
Classes
class ACANFrame
class CMCPCANConnector
class CReadCANFrame
class CSendCANFrame
class ICANConnector
Typedefs
typedef void(* SetupFiltersAndMasks) (ICANConnector &pConnector)
Functions
static bool InitializeCAN (ICANConnector &pCAN, SetupFiltersAndMasks pSetupFunc=nullptr)
Detailed Description
Regroup CAN objects
Typedef Documentation
SetupFiltersAndMasks
typedef void(* CAN::SetupFiltersAndMasks) (ICANConnector &pConnector)
Function pointer to use to define startup masks and filters
Parameters
[in] pConnector Connector to work on
Definition at line 31 of file ICANConnector.h.
Function Documentation
InitializeCAN()
static bool CAN::InitializeCAN (ICANConnector & pCAN, SetupFiltersAndMasks pSetupFunc = nullptr) static
Initialize the CAN bus
Parameters
[in] pCAN CAN connector to initialize
[in] pSetupFunc Setup function to use
Returns
True on success, false otherwise
Definition at line 321 of file ICANConnector.h.
References CAN::ICANConnector::HasError(), CAN::ICANConnector::HasMessages(), CAN::ICANConnector::Initialize(), and CAN::ICANConnector::Read().
     {
         // Declare everything we need
         char            lTestCounter    = 0 ;
         unsigned long   lCANId          = 0 ;
         unsigned char   lLength         = 0 ;
         unsigned char   lData[8]        = { 0, 0, 0, 0, 0, 0, 0, 0 } ;
         // While CAN initialization fails
         while (!pCAN.Initialize(pSetupFunc))
         {
             // More than 20 tries ?
             if (lTestCounter++ > 20)
             {
                 // Failed !
                 return false ;
             }
             // Wait some time before trying again
             DELAY(100) ;
         }
         // Unstack all possible message we might have received even if filters have been set accordingly
         while (pCAN.HasMessages())
         {
             pCAN.Read(lCANId, lLength, lData) ;
         }
         // Valid if no errors so far !
         return !pCAN.HasError() ;
     }